databases:
  - name: eduforge-db
    databaseName: eduforge
    user: eduforge_user
    plan: free

services:
  - type: web
    name: eduforge-backend
    env: python
    # This points to the build.sh script you created
    buildCommand: "./build.sh"
    # This points to backend/wsgi.py (based on your folder structure)
    startCommand: "gunicorn backend.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: eduforge-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: ALLOWED_HOSTS
        value: "*"